CREATE TABLE SENSES (
    SENSE_ID numeric(30) PRIMARY KEY,
    SENSE_TYPE varchar(255) NOT NULL,
    SENSE_STRENGTH varchar(255) NOT NULL,
    SENSE_INHIBITIONS varchar(255) NOT NULL,
    SENSE_BIOLOGICAL_PATHWAYS varchar(255) NOT NULL,
    SUBJECT_ID numeric(30) NOT NULL)
    CONSTRAINT SUB_SUBJECT_ID_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID);
CREATE TABLE STIMULUS (
    STIMULUS_ID numeric(30) PRIMARY KEY,
    STIMULUS_TYPE varchar(255) NOT NULL,
    STIMULUS_STRENGTH varchar(255) NOT NULL,
    STIMULUS_INHIBITIONS varchar(255) NOT NULL,
    STIMULUS_BIOLOGICAL_PATHWAYS varchar(255) NOT NULL,
    SUBJECT_ID numeric(30) NOT NULL,
    CONSTRAINT SUB_SUBJECT_ID_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID));

CREATE TABLE RESPONSES (
    RESPONSE_ID numeric(30) PRIMARY KEY,
    RESPONSE_TYPE varchar(255) NOT NULL,
    RESPONSE_STRENGTH varchar(255) NOT NULL,
    RESPONSE_INHIBITIONS varchar(255) NOT NULL,
    RESPONSE_BIOLOGICAL_PATHWAYS varchar(255) NOT NULL,
    SUBJECT_ID numeric(30) NOT NULL),
    CONSTRAINT SUB_SUBJECT_ID_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID));

CREATE TABLE SUBJECTS (
    SUBJECT_ID numeric(30) PRIMARY KEY,
    SUBJECT_NAME varchar(255) NOT NULL,
    SUBJECT_DOB varchar(255) NOT NULL,
    SUBJECT_GENETIC_TRANSCRIPT varchar(255),
    SUBJECT_IMPAIRMENTS varchar(255));
CREATE TABLE MEASUREMENTS (
    MEASUREMENT_ID numeric(30) PRIMARY KEY,
    MEASUREMENT_TYPE varchar(255) NOT NULL,
    MEASUREMENT_INHIBITIONS varchar(255)NOT NULL,
    MEASUREMENT_BIOLOGICAL_PATHWAYS varchar(255)NOT NULL,
    MEASUREMENT_WHOLE_BRAIN_RESPONSE_ACTIVITY varchar(255)NOT NULL,
    MEASUREMENT_NOTABLE_NEURAL_RESPONSES varchar(255),
    SUBJECT_ID numeric(30) NOT NULL,
    SENSE_ID numeric(30),
    STIMULUS_TYPE varchar(255) NOT NULL,
    STIMULUS_STRENGTH varchar(255) NOT NULL,
    RESPONSE_STRENGTH varchar(255) NOT NULL,
    CONSTRAINT SUB_SUBJECT_ID_FK FOREIGN KEY(SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID),
    CONSTRAINT SEN_SENSE_ID_FK FOREIGN KEY(SENSE_ID) REFERENCES SENSES(SENSE_ID),
    CONSTRAINT STI_STIMULUS_TYPE_FK FOREIGN KEY(STIMULUS_TYPE) REFERENCES STIMULUS(STIMULUS_TYPE),
    CONSTRAINT STI_STIMULUS_STRENGTH_FK FOREIGN KEY(STIMULUS_STRENGTH) REFERENCES STIMULUS(STIMULUS_STRENGTH),
    CONSTRAINT RES_RESPONSE_STRENGTH_FK FOREIGN KEY(RESPONSE_STRENGTH) REFERENCES RESPONSES(RESPONSE_STRENGTH));

"""Create unique indexes on all natural keys"""
CREATE UNIQUE INDEX SEN_SENSE_TYPE_UX ON SENSES(SENSE_TYPE);
CREATE UNIQUE INDEX SEN_SENSE_STRENGTH_UX ON SENSES(SENSE_STRENGTH);
CREATE UNIQUE INDEX SEN_SENSE_INHIBITIONS_UX ON SENSES(SENSE_INHIBITIONS);
CREATE UNIQUE INDEX SEN_SENSE_BIOLOGICAL_PATHWAYS_UX ON SENSES(SENSE_BIOLOGICAL_PATHWAYS);

CREATE UNIQUE INDEX STI_STIMULUS_TYPE_UX ON STIMULUS(STIMULUS_TYPE);
CREATE UNIQUE INDEX STI_STIMULUS_STRENGTH_UX ON STIMULUS(STIMULUS_STRENGTH);
CREATE UNIQUE INDEX STI_STIMULUS_INHIBITIONS_UX ON STIMULUS(STIMULUS_INHIBITIONS);
CREATE UNIQUE INDEX STI_STIMULUS_BIOLOGICAL_PATHWAYS_UX ON STIMULUS(STIMULUS_BIOLOGICAL_PATHWAYS);

CREATE UNIQUE INDEX RES_RESPONSE_TYPE_UX ON RESPONSES(RESPONSE_TYPE);
CREATE UNIQUE INDEX RES_RESPONSE_STRENGTH_UX ON RESPONSES(RESPONSE_STRENGTH);
CREATE UNIQUE INDEX RES_RESPONSE_INHIBITIONS_UX ON RESPONSES(RESPONSE_INHIBITIONS);
CREATE UNIQUE INDEX RES_RESPONSE_BIOLOGICAL_PATHWAYS_UX ON RESPONSES(RESPONSE_BIOLOGICAL_PATHWAYS);
CREATE UNIQUE INDEX SUB_SUBJECT_NAME_UX ON SUBJECTS(SUBJECT_NAME);
CREATE UNIQUE INDEX SUB_SUBJECT_DOB_UX ON SUBJECTS(SUBJECT_DOB);
CREATE UNIQUE INDEX SUB_SUBJECT_GENETIC_TRANSCRIPT_UX ON SUBJECTS(SUBJECT_GENETIC_TRANSCRIPT);
CREATE UNIQUE INDEX SUB_SUBJECT_IMPAIRMENTS_UX ON SUBJECTS(SUBJECT_IMPAIRMENTS);
CREATE UNIQUE INDEX MEA_MEASUREMENT_STRENGTH_RESULTS_UX ON MEASUREMENTS(MEASUREMENT_STRENGTH_RESULTS);
CREATE UNIQUE INDEX MEA_MEASUREMENT_INHIBITIONS_UX ON MEASUREMENTS(MEASUREMENT_INHIBITIONS);
CREATE UNIQUE INDEX MEA_MEASUREMENT_BIOLOGICAL_PATHWAYS_UX ON MEASUREMENTS(MEASUREMENT_BIOLOGICAL_PATHWAYS);
CREATE UNIQUE INDEX MEA_MEASUREMENT_WHOLE_BRAIN_RESPONSE_ACTIVITY_UX ON MEASUREMENTS(MEASUREMENT_WHOLE_BRAIN_RESPONSE_ACTIVITY);
CREATE UNIQUE INDEX MEA_MEASUREMENT_NOTABLE_NEURAL_RESPONSES_UX ON MEASUREMENTS(MEASUREMENT_NOTABLE_NEURAL_RESPONSES);

CREATE INDEX MEA_SUBJECT_ID_FK ON SUBJECTS(SUBJECT_ID);
CREATE INDEX MEA_SENSE_ID_FK ON SENSES(SENSE_ID);
CREATE INDEX MEA_STIMULUS_TYPE_FK ON STIMULUS(STIMULUS_TYPE);
CREATE INDEX MEA_STIMULUS_STRENGTH_FK ON STIMULUS(STIMULUS_STRENGTH);
CREATE INDEX MEA_RESPONSE_STRENGTH_FK ON RESPONSES(RESPONSE_STRENGTH);

CREATE INDEX MEA_WHOLE_BRAIN_RESPONSE_ACTIVITY_IDX ON MEASUREMENTS(WHOLE_BRAIN_RESPONSE_ACTIVITY);
CREATE INDEX MEA_NOTABLE_NEURAL_RESPONSESY_IDX ON MEASUREMENTS(WHOLE_BRAIN_RESPONSE_ACTIVITY);

"""The business purpose of this view is to review stimulus ID, type, and strength all at once."""
CREATE OR REPLACE VIEW VW_STI AS
    SELECT STIMULUS_ID, STIMULUS_TYPE, STIMULUS_STRENGTH FROM STIMULUS;
    
"""The business purpose of this view is to be able to automatically review response ID, type, and strength all at once. """
CREATE OR REPLACE VIEW VW_RES AS
    SELECT RESPONSE_ID, RESPONSE_TYPE, RESPONSE_STRENGTH FROM RESPONSES;
    
"""The business purpose of this view is to be able to automatically to review subject ID, name, and date of birth all at once."""
CREATE OR REPLACE VIEW VW_SUB AS
    SELECT SUBJECT_ID, SUBJECT_NAME, SUBJECT_DOB FROM SUBJECTS;
    
"""The business purpose of this view is to be able to automatically to review stimulus ID, type, and strength all at once."""
CREATE OR REPLACE VIEW VW_SEN AS
    SELECT SENSE_ID, SENSE_TYPE, SENSE_STRENGTH FROM SENSES;

"""The business purpose of this view is to be able to automatically to review measurement ID, type, strength, and whole brain activity all at once."""
CREATE OR REPLACE VIEW VW_MEA AS
    SELECT MEASUREMENT_ID, MEASUREMENT_TYPE, MEASUREMENT_STRENGTH, MEASUREMENT_WHOLE_BRAIN_RESPONSE_ACTIVITY FROM MEASUREMENTS;

CREATE SEQUENCE seq_mea_id;
CREATE SEQUENCE seq_sub_id;
CREATE SEQUENCE seq_res_id;
CREATE SEQUENCE seq_sen_id;
CREATE SEQUENCE seq_sti_id;

"""The business purpose of this trigger is to populate the STIMULUS Table's surrogate key and audit columns with appropriate values"""
CREATE OR REPLACE TRIGGER BIUR_STI_TRG
  BEFORE INSERT OR UPDATE ON STIMULUS
  FOR EACH ROW
    BEGIN
        IF INSERTING THEN
            IF :NEW.created_by IS NULL THEN
                :NEW.created_by := USER;
            END IF;
            IF :NEW.date_created IS NULL THEN
                :NEW.date_created := SYSDATE;
            END IF;
        END IF;
        IF INSERTING OR UPDATING THEN
            :NEW.modified_by := USER;
            :NEW.date_modified := SYSDATE;
        END IF;
END;
/
"""The business purpose of this trigger is to populate the SUBJECTS Table's surrogate key and audit columns with appropriate values"""
CREATE OR REPLACE TRIGGER BIUR_SUB_TRG
  BEFORE INSERT OR UPDATE ON SUBJECTS
  FOR EACH ROW
BEGIN
        IF INSERTING THEN
            IF :NEW.created_by IS NULL THEN
                :NEW.created_by := USER;
            END IF;
            IF :NEW.date_created IS NULL THEN
                :NEW.date_created := SYSDATE;
            END IF;
        END IF;
        IF INSERTING OR UPDATING THEN
            :NEW.modified_by := USER;
            :NEW.date_modified := SYSDATE;
        END IF;
END;
/

"""The business purpose of this trigger is to populate the RESPONSES Table's surrogate key and audit columns with appropriate values"""
CREATE OR REPLACE TRIGGER BIUR_RES_TRG
  BEFORE INSERT OR UPDATE ON RESPONSES
  FOR EACH ROW
BEGIN
        IF INSERTING THEN
            IF :NEW.created_by IS NULL THEN
                :NEW.created_by := USER;
            END IF;
            IF :NEW.date_created IS NULL THEN
                :NEW.date_created := SYSDATE;
            END IF;
        END IF;
        IF INSERTING OR UPDATING THEN
            :NEW.modified_by := USER;
            :NEW.date_modified := SYSDATE;
        END IF;
END;
/

"""The business purpose of this trigger is to populate the MEASUREMENTS Table's surrogate key and audit columns with appropriate values"""
CREATE OR REPLACE TRIGGER BIUR_MEA_TRG
  BEFORE INSERT OR UPDATE ON MEASUREMENTS
  FOR EACH ROW
BEGIN
        IF INSERTING THEN
            IF :NEW.created_by IS NULL THEN
                :NEW.created_by := USER;
            END IF;
            IF :NEW.date_created IS NULL THEN
                :NEW.date_created := SYSDATE;
            END IF;
        END IF;
        IF INSERTING OR UPDATING THEN
            :NEW.modified_by := USER;
            :NEW.date_modified := SYSDATE;
        END IF;
END;
/

"""The business purpose of this trigger is to populate the SENSES Table's surrogate key and audit columns with appropriate values"""
CREATE OR REPLACE TRIGGER BIUR_SEN_TRG
  BEFORE INSERT OR UPDATE ON SENSES
  FOR EACH ROW
BEGIN
        IF INSERTING THEN
            IF :NEW.created_by IS NULL THEN
                :NEW.created_by := USER;
            END IF;
            IF :NEW.date_created IS NULL THEN
                :NEW.date_created := SYSDATE;
            END IF;
        END IF;
        IF INSERTING OR UPDATING THEN
            :NEW.modified_by := USER;
            :NEW.date_modified := SYSDATE;
        END IF;
END;
/

SELECT TABLE_NAME FROM USER_TABLES;  
SELECT OBJECT_NAME, STATUS, CREATED, LAST_DDL_TIME FROM USER_OBJECTS;
